[env:teensy40]
platform = teensy@5.1.0
board = teensy40
framework = arduino

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio

board_microros_transport = serial
board_microros_distro = kilted